version: "3.8"

services:
  frontend:
    build:
      context: ./amadeus-travel
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
    networks:
      - amadeus-network
    restart: unless-stopped

  backend:
    build:
      context: ./amadeus-travel-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
    networks:
      - amadeus-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  amadeus-network:
    driver: bridge

volumes:
  amadeus-data:
